VariantDir("build", ".", duplicate=False)

env = Environment(CXXFLAGS=["-std=c++11"])

# Add support for generating compilation database files
env.Tool("compilation_db")
compiledb = env.CompilationDatabase("compile_commands.json")
env.Alias("compiledb", compiledb)

if ARGUMENTS.get('debug', 0):
    flags = ['-g', '-O0']
    env.Append(CFLAGS=flags, CXXFLAGS=flags)
if ARGUMENTS.get('ccache', 0):
    env.Prepend(CC="ccache ", CXX="ccache ")
env.SharedLibrary(['hello-gdextension-lite.cpp', '../gdextension-lite/gdextension-lite-one.c'])
