env = Environment()
if ARGUMENTS.get('debug', 0):
    env.Append(CFLAGS=['-g', '-O0'])
if ARGUMENTS.get('ccache', 0):
    env.Prepend(CC="ccache ")
env.SharedLibrary(['hello-gdextension-lite.c', 'gdextension-lite-implementation.c'])
