VariantDir("build", ".", duplicate=False)

env = Environment(
    CFLAGS=["-flto"],
    CPPPATH=[".."],
)

# Add support for generating compilation database files
env.Tool("compilation_db")
compiledb = env.CompilationDatabase("compile_commands.json")
env.Alias("compiledb", compiledb)

if ARGUMENTS.get('debug', 0):
    flags = ['-g', '-O0']
    env.Append(CFLAGS=flags, CXXFLAGS=flags)
else:
    flags = ['-O2']
    env.Append(CFLAGS=flags, CXXFLAGS=flags)
if ARGUMENTS.get('ccache', 0):
    env.Prepend(CC="ccache ", CXX="ccache ")
library = env.SharedLibrary(['hello-gdextension-lite.c', '../gdextension-lite/gdextension-lite-one.c'])

Default(library)
