/** @file
 * gdextension-interface.h -- Global GDExtension interface API pointer
 */
#ifndef __GDEXTENSION_LITE_INTERFACE_H__
#define __GDEXTENSION_LITE_INTERFACE_H__

#include "gdextension/gdextension_interface.h"

void gdextension_lite_initialize_interface(const GDExtensionInterfaceGetProcAddress get_proc_address);

extern GDExtensionInterfaceGetVariantFromTypeConstructor godot_get_variant_from_type_constructor;
extern GDExtensionInterfaceGetVariantToTypeConstructor godot_get_variant_to_type_constructor;
extern GDExtensionInterfaceVariantGetPtrOperatorEvaluator godot_variant_get_ptr_operator_evaluator;
extern GDExtensionInterfaceVariantGetPtrBuiltinMethod godot_variant_get_ptr_builtin_method;
extern GDExtensionInterfaceVariantGetPtrConstructor godot_variant_get_ptr_constructor;
extern GDExtensionInterfaceVariantGetPtrDestructor godot_variant_get_ptr_destructor;
extern GDExtensionInterfaceVariantGetPtrSetter godot_variant_get_ptr_setter;
extern GDExtensionInterfaceVariantGetPtrGetter godot_variant_get_ptr_getter;
extern GDExtensionInterfaceVariantGetPtrIndexedSetter godot_variant_get_ptr_indexed_setter;
extern GDExtensionInterfaceVariantGetPtrIndexedGetter godot_variant_get_ptr_indexed_getter;
extern GDExtensionInterfaceVariantGetPtrKeyedSetter godot_variant_get_ptr_keyed_setter;
extern GDExtensionInterfaceVariantGetPtrKeyedGetter godot_variant_get_ptr_keyed_getter;
extern GDExtensionInterfaceVariantGetConstantValue godot_variant_get_constant_value;
extern GDExtensionInterfaceVariantGetPtrUtilityFunction godot_variant_get_ptr_utility_function;
extern GDExtensionInterfaceVariantDestroy godot_variant_destroy;

extern GDExtensionInterfaceStringNewWithLatin1Chars godot_string_new_with_latin1_chars;
extern GDExtensionInterfaceStringNewWithUtf8Chars godot_string_new_with_utf8_chars;
extern GDExtensionInterfaceStringNewWithUtf16Chars godot_string_new_with_utf16_chars;
extern GDExtensionInterfaceStringNewWithUtf32Chars godot_string_new_with_utf32_chars;
extern GDExtensionInterfaceStringNewWithWideChars godot_string_new_with_wide_chars;
extern GDExtensionInterfaceStringNewWithLatin1CharsAndLen godot_string_new_with_latin1_chars_and_len;
extern GDExtensionInterfaceStringNewWithUtf8CharsAndLen godot_string_new_with_utf8_chars_and_len;
extern GDExtensionInterfaceStringNewWithUtf16CharsAndLen godot_string_new_with_utf16_chars_and_len;
extern GDExtensionInterfaceStringNewWithUtf32CharsAndLen godot_string_new_with_utf32_chars_and_len;
extern GDExtensionInterfaceStringNewWithWideCharsAndLen godot_string_new_with_wide_chars_and_len;

extern GDExtensionInterfaceClassdbGetMethodBind godot_classdb_get_method_bind;


#endif

#ifdef GDEXTENSION_LITE_IMPLEMENTATION
#ifndef __GDEXTENSION_LITE_INTERFACE_H_IMPLEMENTATION__
#define __GDEXTENSION_LITE_INTERFACE_H_IMPLEMENTATION__

GDExtensionInterfaceGetVariantFromTypeConstructor godot_get_variant_from_type_constructor;
GDExtensionInterfaceGetVariantToTypeConstructor godot_get_variant_to_type_constructor;
GDExtensionInterfaceVariantGetPtrOperatorEvaluator godot_variant_get_ptr_operator_evaluator;
GDExtensionInterfaceVariantGetPtrBuiltinMethod godot_variant_get_ptr_builtin_method;
GDExtensionInterfaceVariantGetPtrConstructor godot_variant_get_ptr_constructor;
GDExtensionInterfaceVariantGetPtrDestructor godot_variant_get_ptr_destructor;
GDExtensionInterfaceVariantGetPtrSetter godot_variant_get_ptr_setter;
GDExtensionInterfaceVariantGetPtrGetter godot_variant_get_ptr_getter;
GDExtensionInterfaceVariantGetPtrIndexedSetter godot_variant_get_ptr_indexed_setter;
GDExtensionInterfaceVariantGetPtrIndexedGetter godot_variant_get_ptr_indexed_getter;
GDExtensionInterfaceVariantGetPtrKeyedSetter godot_variant_get_ptr_keyed_setter;
GDExtensionInterfaceVariantGetPtrKeyedGetter godot_variant_get_ptr_keyed_getter;
GDExtensionInterfaceVariantGetConstantValue godot_variant_get_constant_value;
GDExtensionInterfaceVariantGetPtrUtilityFunction godot_variant_get_ptr_utility_function;
GDExtensionInterfaceVariantDestroy godot_variant_destroy;

GDExtensionInterfaceStringNewWithLatin1Chars godot_string_new_with_latin1_chars;
GDExtensionInterfaceStringNewWithUtf8Chars godot_string_new_with_utf8_chars;
GDExtensionInterfaceStringNewWithUtf16Chars godot_string_new_with_utf16_chars;
GDExtensionInterfaceStringNewWithUtf32Chars godot_string_new_with_utf32_chars;
GDExtensionInterfaceStringNewWithWideChars godot_string_new_with_wide_chars;
GDExtensionInterfaceStringNewWithLatin1CharsAndLen godot_string_new_with_latin1_chars_and_len;
GDExtensionInterfaceStringNewWithUtf8CharsAndLen godot_string_new_with_utf8_chars_and_len;
GDExtensionInterfaceStringNewWithUtf16CharsAndLen godot_string_new_with_utf16_chars_and_len;
GDExtensionInterfaceStringNewWithUtf32CharsAndLen godot_string_new_with_utf32_chars_and_len;
GDExtensionInterfaceStringNewWithWideCharsAndLen godot_string_new_with_wide_chars_and_len;

GDExtensionInterfaceClassdbGetMethodBind godot_classdb_get_method_bind;

void gdextension_lite_initialize_interface(const GDExtensionInterfaceGetProcAddress get_proc_address) {
	godot_get_variant_from_type_constructor = (GDExtensionInterfaceGetVariantFromTypeConstructor) get_proc_address("get_variant_from_type_constructor");
	godot_get_variant_to_type_constructor = (GDExtensionInterfaceGetVariantToTypeConstructor) get_proc_address("get_variant_to_type_constructor");
	godot_variant_get_ptr_operator_evaluator = (GDExtensionInterfaceVariantGetPtrOperatorEvaluator) get_proc_address("variant_get_ptr_operator_evaluator");
	godot_variant_get_ptr_builtin_method = (GDExtensionInterfaceVariantGetPtrBuiltinMethod) get_proc_address("variant_get_ptr_builtin_method");
	godot_variant_get_ptr_constructor = (GDExtensionInterfaceVariantGetPtrConstructor) get_proc_address("variant_get_ptr_constructor");
	godot_variant_get_ptr_destructor = (GDExtensionInterfaceVariantGetPtrDestructor) get_proc_address("variant_get_ptr_destructor");
	godot_variant_get_ptr_setter = (GDExtensionInterfaceVariantGetPtrSetter) get_proc_address("variant_get_ptr_setter");
	godot_variant_get_ptr_getter = (GDExtensionInterfaceVariantGetPtrGetter) get_proc_address("variant_get_ptr_getter");
	godot_variant_get_ptr_indexed_setter = (GDExtensionInterfaceVariantGetPtrIndexedSetter) get_proc_address("variant_get_ptr_indexed_setter");
	godot_variant_get_ptr_indexed_getter = (GDExtensionInterfaceVariantGetPtrIndexedGetter) get_proc_address("variant_get_ptr_indexed_getter");
	godot_variant_get_ptr_keyed_setter = (GDExtensionInterfaceVariantGetPtrKeyedSetter) get_proc_address("variant_get_ptr_keyed_setter");
	godot_variant_get_ptr_keyed_getter = (GDExtensionInterfaceVariantGetPtrKeyedGetter) get_proc_address("variant_get_ptr_keyed_getter");
	godot_variant_get_constant_value = (GDExtensionInterfaceVariantGetConstantValue) get_proc_address("variant_get_constant_value");
	godot_variant_get_ptr_utility_function = (GDExtensionInterfaceVariantGetPtrUtilityFunction) get_proc_address("variant_get_ptr_utility_function");
	godot_variant_destroy = (GDExtensionInterfaceVariantDestroy) get_proc_address("variant_destroy");
	godot_string_new_with_latin1_chars = (GDExtensionInterfaceStringNewWithLatin1Chars) get_proc_address("string_new_with_latin1_chars");
	godot_string_new_with_utf8_chars = (GDExtensionInterfaceStringNewWithUtf8Chars) get_proc_address("string_new_with_utf8_chars");
	godot_string_new_with_utf16_chars = (GDExtensionInterfaceStringNewWithUtf16Chars) get_proc_address("string_new_with_utf16_chars");
	godot_string_new_with_utf32_chars = (GDExtensionInterfaceStringNewWithUtf32Chars) get_proc_address("string_new_with_utf32_chars");
	godot_string_new_with_wide_chars = (GDExtensionInterfaceStringNewWithWideChars) get_proc_address("string_new_with_wide_chars");
	godot_string_new_with_latin1_chars_and_len = (GDExtensionInterfaceStringNewWithLatin1CharsAndLen) get_proc_address("string_new_with_latin1_chars_and_len");
	godot_string_new_with_utf8_chars_and_len = (GDExtensionInterfaceStringNewWithUtf8CharsAndLen) get_proc_address("string_new_with_utf8_chars_and_len");
	godot_string_new_with_utf16_chars_and_len = (GDExtensionInterfaceStringNewWithUtf16CharsAndLen) get_proc_address("string_new_with_utf16_chars_and_len");
	godot_string_new_with_utf32_chars_and_len = (GDExtensionInterfaceStringNewWithUtf32CharsAndLen) get_proc_address("string_new_with_utf32_chars_and_len");
	godot_string_new_with_wide_chars_and_len = (GDExtensionInterfaceStringNewWithWideCharsAndLen) get_proc_address("string_new_with_wide_chars_and_len");
	godot_classdb_get_method_bind = (GDExtensionInterfaceClassdbGetMethodBind) get_proc_address("classdb_get_method_bind");
}

#endif  // __GDEXTENSION_LITE_INTERFACE_H_IMPLEMENTATION__
#endif  // GDEXTENSION_LITE_IMPLEMENTATION
